import { User } from "../../interfaces/User";

export class MockData {
  public static User: User = {
    id: 'user123',
    name: 'Test User',
    email: 'testuser@example.com',
    xp: 1500,
    level: 5,
    currentCard: 42,
    settings: {
      proficiency: 'intermediate',
      audioEnabled: true,
      slowAudioEnabled: false,
      autoPlayEnabled: true,
      dailyReminders: true,
      streakReminders: false,
      achievementNotifications: true,
    },
    stats: {
      wordsLearned: 120,
      masteredWords: 80,
      difficultWords: 10,
      totalWords: 200,
      dailyGoal: 20,
      streakDays: 15,
      studyTime: 300, // in minutes
      achievements: [
        { id: 'achv1', name: 'First Steps', description: 'Learn your first 10 words', dateEarned: new Date('2023-01-15') },
        { id: 'achv2', name: 'Consistency', description: 'Study for 7 consecutive days', dateEarned: new Date('2023-02-01') },
      ],
    },
    selectedCategory: 'Basic Phrases',
    learningMode: 'flashcards',
    currentGrammarTopic: 'Present Tense',
    savedTranslations: [
      { id: 'trans1', originalText: 'Hello', translatedText: 'مرحبا', date: new Date('2023-03-10') },
      { id: 'trans2', originalText: 'Thank you', translatedText: 'شكرا', date: new Date('2023-03-12') },
    ],
    translationHistory: [
      { id: 'trans3', originalText: 'Goodbye', translatedText: 'مع السلامة', date: new Date('2023-03-14') },
      { id: 'trans4', originalText: 'Please', translatedText: 'من فضلك', date: new Date('2023-03-15') },
    ],
  };



  // Generated by ChatGPT with manual enhancements, data model should be changed
  public static vocabularyCategories = {
    greetings_basic: {
      name: "Greetings & Basic Phrases",
      name_arabic: "التحيات والعبارات الأساسية",
      icon: "👋",
      words: [
        { arabic: "أهلاً وسهلاً", pronunciation: "ahlan wa sahlan", english: "hello/welcome", french: "bonjour/bienvenue", usage: "formal_greeting" },
        { arabic: "مرحبا", pronunciation: "marhaba", english: "hello", french: "bonjour", usage: "casual_greeting" },
        { arabic: "صباح الخير", pronunciation: "sabah el kheir", english: "good morning", french: "bonjour", usage: "morning_greeting" },
        { arabic: "مساء الخير", pronunciation: "masa el kheir", english: "good evening", french: "bonsoir", usage: "evening_greeting" },
        { arabic: "تصبح على خير", pronunciation: "tisbah 3ala kheir", english: "good night", french: "bonne nuit", usage: "night_farewell" },
        { arabic: "شكراً", pronunciation: "shukran", english: "thank you", french: "merci", usage: "gratitude" },
        { arabic: "عفواً", pronunciation: "3afwan", english: "you're welcome", french: "de rien", usage: "response_to_thanks" },
        { arabic: "كيفك؟", pronunciation: "kifak?", english: "how are you? (m)", french: "comment allez-vous?", usage: "inquiry_male" },
        { arabic: "كيفِك؟", pronunciation: "kifik?", english: "how are you? (f)", french: "comment allez-vous?", usage: "inquiry_female" },
        { arabic: "منيح", pronunciation: "mnih", english: "good/fine", french: "bien", usage: "status_response" }
      ]
    },
    lebanese_slang: {
      name: "Lebanese Slang & Expressions",
      name_arabic: "العامية والتعابير اللبنانية",
      icon: "💬",
      words: [
        { arabic: "يلا", pronunciation: "yalla", english: "let's go/come on", french: "allons-y", usage: "encouragement" },
        { arabic: "خلص", pronunciation: "khalas", english: "finished/enough", french: "fini/assez", usage: "completion" },
        { arabic: "شو؟", pronunciation: "shu?", english: "what?", french: "quoi?", usage: "question" },
        { arabic: "وين؟", pronunciation: "wayn?", english: "where?", french: "où?", usage: "location_inquiry" },
        { arabic: "بدي", pronunciation: "biddi", english: "I want", french: "je veux", usage: "desire" },
        { arabic: "مخيف", pronunciation: "mukheef", english: "scary (but means awesome!)", french: "effrayant (mais génial!)", usage: "slang_awesome" }
      ]
    },
    emotions_feelings: {
      name: "Emotions & Feelings",
      name_arabic: "المشاعر والأحاسيس",
      icon: "😊",
      words: [
        { arabic: "تعبان", pronunciation: "ta3ban", english: "tired", french: "fatigué", usage: "physical_state" },
        { arabic: "مبسوط", pronunciation: "mabsout", english: "happy", french: "heureux", usage: "positive_emotion" },
        { arabic: "زعلان", pronunciation: "za3lan", english: "upset/angry", french: "fâché", usage: "negative_emotion" },
        { arabic: "خايف", pronunciation: "khayef", english: "scared", french: "effrayé", usage: "fear" },
        { arabic: "فرحان", pronunciation: "farhan", english: "joyful", french: "joyeux", usage: "joy" }
      ]
    }
  };

  public static radioStations = [
    { name: "Radio Delta Lebanon", name_arabic: "راديو دلتا لبنان", frequency: "Various FM", genre: "Arabic Pop, Lebanese Music", description: "Top Arabic radio station" },
    { name: "Virgin Radio Lebanon", name_arabic: "فيرجين راديو لبنان", frequency: "89.5 FM", genre: "Pop, Rock, International", description: "International music station" }
  ];

  public static podcasts = [
    { name: "Learn Levantine Arabic with Livi", host: "Olivia Furber", rating: 4.9, level: "Intermediate", description: "Native speaker interviews" },
    { name: "Real Arabic", rating: 4.7, level: "Beginner", description: "Culture and politics with transcripts" }
  ];

  public static tvShows = [
    { title: "Ya Rayt", title_arabic: "يا ريت", type: "Drama", description: "Lebanese drama perfect for learning", subtitles: ["Arabic", "English"] },
    { title: "Al Hayba", title_arabic: "الهيبة", type: "Action", description: "Popular action series", seasons: 3 }
  ];

  public static culture = {
    traditions: [
      { name: "Dabke Dance", name_arabic: "دبكة", description: "Traditional folk dance performed in lines" },
      { name: "Lebanese Hospitality", name_arabic: "الضيافة اللبنانية", description: "Sacred tradition of welcoming guests" }
    ],
    figures: [
      { name: "Fairuz", name_arabic: "فيروز", title: "Ambassador to the Stars", birth_year: 1935 }
    ]
  };

  public static grammarTopics = [
    { id: "pronouns", title: "Personal Pronouns", description: "Learn Lebanese Arabic personal pronouns" },
    { id: "verbs", title: "Verb Conjugations", description: "Master verb conjugations" }
  ];

  public static newsChannels = [
    { name: "MTV Lebanon", name_arabic: "قناة أم تي في", description: "Leading entertainment and news" },
    { name: "Al Jadeed", name_arabic: "قناة الجديد", description: "Independent news channel" }
  ];

  // Create comprehensive vocabulary
  public static allVocabulary = (Object.keys(MockData.vocabularyCategories) as Array<keyof typeof MockData.vocabularyCategories>)
    .flatMap((key) => {
      const cat = MockData.vocabularyCategories[key];
      return cat.words.map(word => ({
        ...word,
        category: cat.name,
        categoryKey: key
      }));
    });
}

